blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/thetechcollective/thetechcollective.dev/discussions/categories
    about: Please post your support questions in the Discussions section on the content repo.
